/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgreementStatus = { 'repaid' : null } |
  { 'active' : null } |
  { 'partial' : null } |
  { 'defaulted' : null };
export type AssetType = { 'ada' : null } |
  { 'bnb' : null } |
  { 'btc' : null } |
  { 'dot' : null } |
  { 'eth' : null } |
  { 'sol' : null } |
  { 'xrp' : null } |
  { 'matic' : null } |
  { 'aluminum' : null } |
  { 'avax' : null } |
  { 'gold' : null } |
  { 'link' : null } |
  { 'platinum' : null } |
  { 'silver' : null } |
  { 'copper' : null } |
  { 'palladium' : null };
export interface Badge {
  'name' : string,
  'description' : string,
  'earnedAt' : Time,
}
export interface BorrowRequest {
  'id' : bigint,
  'durationDays' : bigint,
  'offeredInterestRate' : number,
  'status' : RequestStatus,
  'createdAt' : Time,
  'collateralType' : AssetType,
  'borrower' : Principal,
  'collateralAmount' : bigint,
  'assetType' : AssetType,
  'amount' : bigint,
}
export interface LoanAgreement {
  'id' : bigint,
  'durationDays' : bigint,
  'status' : AgreementStatus,
  'repayments' : Array<Repayment>,
  'endDate' : Time,
  'totalRepayment' : number,
  'collateralType' : AssetType,
  'borrower' : Principal,
  'collateralAmount' : bigint,
  'interestRate' : number,
  'lender' : Principal,
  'assetType' : AssetType,
  'amount' : bigint,
  'startDate' : Time,
}
export interface LoanListing {
  'id' : bigint,
  'durationDays' : bigint,
  'status' : LoanStatus,
  'createdAt' : Time,
  'minTrustScore' : bigint,
  'collateralType' : AssetType,
  'collateralAmount' : bigint,
  'interestRate' : number,
  'lender' : Principal,
  'assetType' : AssetType,
  'amount' : bigint,
}
export type LoanStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'available' : null } |
  { 'matched' : null };
export interface Repayment {
  'status' : RepaymentStatus,
  'timestamp' : Time,
  'amount' : number,
}
export type RepaymentStatus = { 'late' : null } |
  { 'missed' : null } |
  { 'onTime' : null };
export type Reputation = { 'bronze' : null } |
  { 'novice' : null } |
  { 'gold' : null } |
  { 'diamond' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type RequestStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'matched' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : bigint,
  'principal' : Principal,
  'loansGiven' : bigint,
  'name' : string,
  'badges' : Array<Badge>,
  'trustScore' : bigint,
  'successfulCompletions' : bigint,
  'reputation' : Reputation,
  'loansTaken' : bigint,
  'profileCreatedAt' : Time,
  'activeLoans' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[Principal, string, string], undefined>,
  'createBorrowRequest' : ActorMethod<
    [AssetType, bigint, number, bigint, AssetType, bigint],
    BorrowRequest
  >,
  'createLoanAgreement' : ActorMethod<
    [
      Principal,
      Principal,
      AssetType,
      bigint,
      number,
      bigint,
      AssetType,
      bigint,
    ],
    LoanAgreement
  >,
  'createLoanListing' : ActorMethod<
    [AssetType, bigint, number, bigint, AssetType, bigint, bigint],
    LoanListing
  >,
  'createProfile' : ActorMethod<[string], UserProfile>,
  'getAllBorrowRequests' : ActorMethod<[], Array<BorrowRequest>>,
  'getAllLoanListings' : ActorMethod<[], Array<LoanListing>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBadges' : ActorMethod<[Principal], Array<Badge>>,
  'getBorrowRequestsByBorrower' : ActorMethod<
    [Principal],
    Array<BorrowRequest>
  >,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRepayments' : ActorMethod<[], bigint>,
  'getLoanAgreement' : ActorMethod<[bigint], LoanAgreement>,
  'getLoanListingsByLender' : ActorMethod<[Principal], Array<LoanListing>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'migrateRepayments' : ActorMethod<[], undefined>,
  'recordRepayment' : ActorMethod<[bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByAmountRange' : ActorMethod<
    [bigint, bigint],
    Array<LoanListing>
  >,
  'searchListingsByAsset' : ActorMethod<[AssetType], Array<LoanListing>>,
  'updateTrustScoreAndReputation' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];