/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'ada' : IDL.Null,
  'bnb' : IDL.Null,
  'btc' : IDL.Null,
  'dot' : IDL.Null,
  'eth' : IDL.Null,
  'sol' : IDL.Null,
  'xrp' : IDL.Null,
  'matic' : IDL.Null,
  'aluminum' : IDL.Null,
  'avax' : IDL.Null,
  'gold' : IDL.Null,
  'link' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
  'copper' : IDL.Null,
  'palladium' : IDL.Null,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'matched' : IDL.Null,
});
export const Time = IDL.Int;
export const BorrowRequest = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'offeredInterestRate' : IDL.Float64,
  'status' : RequestStatus,
  'createdAt' : Time,
  'collateralType' : AssetType,
  'borrower' : IDL.Principal,
  'collateralAmount' : IDL.Nat,
  'assetType' : AssetType,
  'amount' : IDL.Nat,
});
export const AgreementStatus = IDL.Variant({
  'repaid' : IDL.Null,
  'active' : IDL.Null,
  'partial' : IDL.Null,
  'defaulted' : IDL.Null,
});
export const RepaymentStatus = IDL.Variant({
  'late' : IDL.Null,
  'missed' : IDL.Null,
  'onTime' : IDL.Null,
});
export const Repayment = IDL.Record({
  'status' : RepaymentStatus,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const LoanAgreement = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'status' : AgreementStatus,
  'repayments' : IDL.Vec(Repayment),
  'endDate' : Time,
  'totalRepayment' : IDL.Float64,
  'collateralType' : AssetType,
  'borrower' : IDL.Principal,
  'collateralAmount' : IDL.Nat,
  'interestRate' : IDL.Float64,
  'lender' : IDL.Principal,
  'assetType' : AssetType,
  'amount' : IDL.Nat,
  'startDate' : Time,
});
export const LoanStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'available' : IDL.Null,
  'matched' : IDL.Null,
});
export const LoanListing = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'status' : LoanStatus,
  'createdAt' : Time,
  'minTrustScore' : IDL.Nat,
  'collateralType' : AssetType,
  'collateralAmount' : IDL.Nat,
  'interestRate' : IDL.Float64,
  'lender' : IDL.Principal,
  'assetType' : AssetType,
  'amount' : IDL.Nat,
});
export const Badge = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : Time,
});
export const Reputation = IDL.Variant({
  'bronze' : IDL.Null,
  'novice' : IDL.Null,
  'gold' : IDL.Null,
  'diamond' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'loansGiven' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'trustScore' : IDL.Nat,
  'successfulCompletions' : IDL.Nat,
  'reputation' : Reputation,
  'loansTaken' : IDL.Nat,
  'profileCreatedAt' : Time,
  'activeLoans' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'createBorrowRequest' : IDL.Func(
      [AssetType, IDL.Nat, IDL.Float64, IDL.Nat, AssetType, IDL.Nat],
      [BorrowRequest],
      [],
    ),
  'createLoanAgreement' : IDL.Func(
      [
        IDL.Principal,
        IDL.Principal,
        AssetType,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        AssetType,
        IDL.Nat,
      ],
      [LoanAgreement],
      [],
    ),
  'createLoanListing' : IDL.Func(
      [AssetType, IDL.Nat, IDL.Float64, IDL.Nat, AssetType, IDL.Nat, IDL.Nat],
      [LoanListing],
      [],
    ),
  'createProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getAllBorrowRequests' : IDL.Func([], [IDL.Vec(BorrowRequest)], ['query']),
  'getAllLoanListings' : IDL.Func([], [IDL.Vec(LoanListing)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBadges' : IDL.Func([IDL.Principal], [IDL.Vec(Badge)], ['query']),
  'getBorrowRequestsByBorrower' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BorrowRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRepayments' : IDL.Func([], [IDL.Nat], ['query']),
  'getLoanAgreement' : IDL.Func([IDL.Nat], [LoanAgreement], ['query']),
  'getLoanListingsByLender' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LoanListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'migrateRepayments' : IDL.Func([], [], []),
  'recordRepayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListingsByAmountRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LoanListing)],
      ['query'],
    ),
  'searchListingsByAsset' : IDL.Func(
      [AssetType],
      [IDL.Vec(LoanListing)],
      ['query'],
    ),
  'updateTrustScoreAndReputation' : IDL.Func([IDL.Principal, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'ada' : IDL.Null,
    'bnb' : IDL.Null,
    'btc' : IDL.Null,
    'dot' : IDL.Null,
    'eth' : IDL.Null,
    'sol' : IDL.Null,
    'xrp' : IDL.Null,
    'matic' : IDL.Null,
    'aluminum' : IDL.Null,
    'avax' : IDL.Null,
    'gold' : IDL.Null,
    'link' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
    'copper' : IDL.Null,
    'palladium' : IDL.Null,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'matched' : IDL.Null,
  });
  const Time = IDL.Int;
  const BorrowRequest = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'offeredInterestRate' : IDL.Float64,
    'status' : RequestStatus,
    'createdAt' : Time,
    'collateralType' : AssetType,
    'borrower' : IDL.Principal,
    'collateralAmount' : IDL.Nat,
    'assetType' : AssetType,
    'amount' : IDL.Nat,
  });
  const AgreementStatus = IDL.Variant({
    'repaid' : IDL.Null,
    'active' : IDL.Null,
    'partial' : IDL.Null,
    'defaulted' : IDL.Null,
  });
  const RepaymentStatus = IDL.Variant({
    'late' : IDL.Null,
    'missed' : IDL.Null,
    'onTime' : IDL.Null,
  });
  const Repayment = IDL.Record({
    'status' : RepaymentStatus,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const LoanAgreement = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'status' : AgreementStatus,
    'repayments' : IDL.Vec(Repayment),
    'endDate' : Time,
    'totalRepayment' : IDL.Float64,
    'collateralType' : AssetType,
    'borrower' : IDL.Principal,
    'collateralAmount' : IDL.Nat,
    'interestRate' : IDL.Float64,
    'lender' : IDL.Principal,
    'assetType' : AssetType,
    'amount' : IDL.Nat,
    'startDate' : Time,
  });
  const LoanStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'available' : IDL.Null,
    'matched' : IDL.Null,
  });
  const LoanListing = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'status' : LoanStatus,
    'createdAt' : Time,
    'minTrustScore' : IDL.Nat,
    'collateralType' : AssetType,
    'collateralAmount' : IDL.Nat,
    'interestRate' : IDL.Float64,
    'lender' : IDL.Principal,
    'assetType' : AssetType,
    'amount' : IDL.Nat,
  });
  const Badge = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : Time,
  });
  const Reputation = IDL.Variant({
    'bronze' : IDL.Null,
    'novice' : IDL.Null,
    'gold' : IDL.Null,
    'diamond' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'loansGiven' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'trustScore' : IDL.Nat,
    'successfulCompletions' : IDL.Nat,
    'reputation' : Reputation,
    'loansTaken' : IDL.Nat,
    'profileCreatedAt' : Time,
    'activeLoans' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'createBorrowRequest' : IDL.Func(
        [AssetType, IDL.Nat, IDL.Float64, IDL.Nat, AssetType, IDL.Nat],
        [BorrowRequest],
        [],
      ),
    'createLoanAgreement' : IDL.Func(
        [
          IDL.Principal,
          IDL.Principal,
          AssetType,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          AssetType,
          IDL.Nat,
        ],
        [LoanAgreement],
        [],
      ),
    'createLoanListing' : IDL.Func(
        [AssetType, IDL.Nat, IDL.Float64, IDL.Nat, AssetType, IDL.Nat, IDL.Nat],
        [LoanListing],
        [],
      ),
    'createProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getAllBorrowRequests' : IDL.Func([], [IDL.Vec(BorrowRequest)], ['query']),
    'getAllLoanListings' : IDL.Func([], [IDL.Vec(LoanListing)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBadges' : IDL.Func([IDL.Principal], [IDL.Vec(Badge)], ['query']),
    'getBorrowRequestsByBorrower' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BorrowRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRepayments' : IDL.Func([], [IDL.Nat], ['query']),
    'getLoanAgreement' : IDL.Func([IDL.Nat], [LoanAgreement], ['query']),
    'getLoanListingsByLender' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LoanListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'migrateRepayments' : IDL.Func([], [], []),
    'recordRepayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListingsByAmountRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LoanListing)],
        ['query'],
      ),
    'searchListingsByAsset' : IDL.Func(
        [AssetType],
        [IDL.Vec(LoanListing)],
        ['query'],
      ),
    'updateTrustScoreAndReputation' : IDL.Func(
        [IDL.Principal, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };