/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: bigint;
    principal: Principal;
    loansGiven: bigint;
    name: string;
    badges: Array<Badge>;
    trustScore: bigint;
    successfulCompletions: bigint;
    reputation: Reputation;
    loansTaken: bigint;
    profileCreatedAt: Time;
    activeLoans: bigint;
}
export type Time = bigint;
export interface BorrowRequest {
    id: bigint;
    durationDays: bigint;
    offeredInterestRate: number;
    status: RequestStatus;
    createdAt: Time;
    collateralType: AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    assetType: AssetType;
    amount: bigint;
}
export interface Badge {
    name: string;
    description: string;
    earnedAt: Time;
}
export interface LoanListing {
    id: bigint;
    durationDays: bigint;
    status: LoanStatus;
    createdAt: Time;
    minTrustScore: bigint;
    collateralType: AssetType;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: AssetType;
    amount: bigint;
}
export interface Repayment {
    status: RepaymentStatus;
    timestamp: Time;
    amount: number;
}
export interface LoanAgreement {
    id: bigint;
    durationDays: bigint;
    status: AgreementStatus;
    repayments: Array<Repayment>;
    endDate: Time;
    totalRepayment: number;
    collateralType: AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: AssetType;
    amount: bigint;
    startDate: Time;
}
export enum AgreementStatus {
    repaid = "repaid",
    active = "active",
    partial = "partial",
    defaulted = "defaulted"
}
export enum AssetType {
    ada = "ada",
    bnb = "bnb",
    btc = "btc",
    dot = "dot",
    eth = "eth",
    sol = "sol",
    xrp = "xrp",
    matic = "matic",
    aluminum = "aluminum",
    avax = "avax",
    gold = "gold",
    link = "link",
    platinum = "platinum",
    silver = "silver",
    copper = "copper",
    palladium = "palladium"
}
export enum LoanStatus {
    cancelled = "cancelled",
    completed = "completed",
    available = "available",
    matched = "matched"
}
export enum RepaymentStatus {
    late = "late",
    missed = "missed",
    onTime = "onTime"
}
export enum Reputation {
    bronze = "bronze",
    novice = "novice",
    gold = "gold",
    diamond = "diamond",
    platinum = "platinum",
    silver = "silver"
}
export enum RequestStatus {
    cancelled = "cancelled",
    open = "open",
    completed = "completed",
    matched = "matched"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardBadge(user: Principal, name: string, description: string): Promise<void>;
    createBorrowRequest(assetType: AssetType, amount: bigint, offeredInterestRate: number, durationDays: bigint, collateralType: AssetType, collateralAmount: bigint): Promise<BorrowRequest>;
    createLoanAgreement(lender: Principal, borrower: Principal, assetType: AssetType, amount: bigint, interestRate: number, durationDays: bigint, collateralType: AssetType, collateralAmount: bigint): Promise<LoanAgreement>;
    createLoanListing(assetType: AssetType, amount: bigint, interestRate: number, durationDays: bigint, collateralType: AssetType, collateralAmount: bigint, minTrustScore: bigint): Promise<LoanListing>;
    createProfile(name: string): Promise<UserProfile>;
    getAllBorrowRequests(): Promise<Array<BorrowRequest>>;
    getAllLoanListings(): Promise<Array<LoanListing>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getBadges(user: Principal): Promise<Array<Badge>>;
    getBorrowRequestsByBorrower(borrower: Principal): Promise<Array<BorrowRequest>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentRepayments(): Promise<bigint>;
    getLoanAgreement(id: bigint): Promise<LoanAgreement>;
    getLoanListingsByLender(lender: Principal): Promise<Array<LoanListing>>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    migrateRepayments(): Promise<void>;
    recordRepayment(agreementId: bigint, amount: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListingsByAmountRange(minAmount: bigint, maxAmount: bigint): Promise<Array<LoanListing>>;
    searchListingsByAsset(assetType: AssetType): Promise<Array<LoanListing>>;
    updateTrustScoreAndReputation(user: Principal, delta: bigint): Promise<void>;
}
import type { AgreementStatus as _AgreementStatus, AssetType as _AssetType, Badge as _Badge, BorrowRequest as _BorrowRequest, LoanAgreement as _LoanAgreement, LoanListing as _LoanListing, LoanStatus as _LoanStatus, Repayment as _Repayment, RepaymentStatus as _RepaymentStatus, Reputation as _Reputation, RequestStatus as _RequestStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardBadge(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, arg1, arg2);
            return result;
        }
    }
    async createBorrowRequest(arg0: AssetType, arg1: bigint, arg2: number, arg3: bigint, arg4: AssetType, arg5: bigint): Promise<BorrowRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createBorrowRequest(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_BorrowRequest_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBorrowRequest(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_BorrowRequest_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLoanAgreement(arg0: Principal, arg1: Principal, arg2: AssetType, arg3: bigint, arg4: number, arg5: bigint, arg6: AssetType, arg7: bigint): Promise<LoanAgreement> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoanAgreement(arg0, arg1, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_LoanAgreement_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoanAgreement(arg0, arg1, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_LoanAgreement_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLoanListing(arg0: AssetType, arg1: bigint, arg2: number, arg3: bigint, arg4: AssetType, arg5: bigint, arg6: bigint): Promise<LoanListing> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoanListing(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_LoanListing_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoanListing(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_LoanListing_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0);
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0);
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBorrowRequests(): Promise<Array<BorrowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBorrowRequests();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBorrowRequests();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLoanListings(): Promise<Array<LoanListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoanListings();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoanListings();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBadges(arg0: Principal): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBadges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBadges(arg0);
            return result;
        }
    }
    async getBorrowRequestsByBorrower(arg0: Principal): Promise<Array<BorrowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBorrowRequestsByBorrower(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBorrowRequestsByBorrower(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentRepayments(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRepayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRepayments();
            return result;
        }
    }
    async getLoanAgreement(arg0: bigint): Promise<LoanAgreement> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanAgreement(arg0);
                return from_candid_LoanAgreement_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanAgreement(arg0);
            return from_candid_LoanAgreement_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanListingsByLender(arg0: Principal): Promise<Array<LoanListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanListingsByLender(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanListingsByLender(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async migrateRepayments(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateRepayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateRepayments();
            return result;
        }
    }
    async recordRepayment(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordRepayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordRepayment(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchListingsByAmountRange(arg0: bigint, arg1: bigint): Promise<Array<LoanListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByAmountRange(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByAmountRange(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchListingsByAsset(arg0: AssetType): Promise<Array<LoanListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByAsset(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByAsset(to_candid_AssetType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrustScoreAndReputation(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrustScoreAndReputation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrustScoreAndReputation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AgreementStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgreementStatus): AgreementStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AssetType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BorrowRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BorrowRequest): BorrowRequest {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LoanAgreement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanAgreement): LoanAgreement {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LoanListing_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanListing): LoanListing {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LoanStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentStatus): RepaymentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Repayment_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Repayment): Repayment {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Reputation_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reputation): Reputation {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    status: _AgreementStatus;
    repayments: Array<_Repayment>;
    endDate: _Time;
    totalRepayment: number;
    collateralType: _AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: _AssetType;
    amount: bigint;
    startDate: _Time;
}): {
    id: bigint;
    durationDays: bigint;
    status: AgreementStatus;
    repayments: Array<Repayment>;
    endDate: Time;
    totalRepayment: number;
    collateralType: AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: AssetType;
    amount: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        status: from_candid_AgreementStatus_n13(_uploadFile, _downloadFile, value.status),
        repayments: from_candid_vec_n15(_uploadFile, _downloadFile, value.repayments),
        endDate: value.endDate,
        totalRepayment: value.totalRepayment,
        collateralType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.collateralType),
        borrower: value.borrower,
        collateralAmount: value.collateralAmount,
        interestRate: value.interestRate,
        lender: value.lender,
        assetType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.assetType),
        amount: value.amount,
        startDate: value.startDate
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RepaymentStatus;
    timestamp: _Time;
    amount: number;
}): {
    status: RepaymentStatus;
    timestamp: Time;
    amount: number;
} {
    return {
        status: from_candid_RepaymentStatus_n18(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    status: _LoanStatus;
    createdAt: _Time;
    minTrustScore: bigint;
    collateralType: _AssetType;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: _AssetType;
    amount: bigint;
}): {
    id: bigint;
    durationDays: bigint;
    status: LoanStatus;
    createdAt: Time;
    minTrustScore: bigint;
    collateralType: AssetType;
    collateralAmount: bigint;
    interestRate: number;
    lender: Principal;
    assetType: AssetType;
    amount: bigint;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        status: from_candid_LoanStatus_n22(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        minTrustScore: value.minTrustScore,
        collateralType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.collateralType),
        collateralAmount: value.collateralAmount,
        interestRate: value.interestRate,
        lender: value.lender,
        assetType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.assetType),
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    loansGiven: bigint;
    name: string;
    badges: Array<_Badge>;
    trustScore: bigint;
    successfulCompletions: bigint;
    reputation: _Reputation;
    loansTaken: bigint;
    profileCreatedAt: _Time;
    activeLoans: bigint;
}): {
    id: bigint;
    principal: Principal;
    loansGiven: bigint;
    name: string;
    badges: Array<Badge>;
    trustScore: bigint;
    successfulCompletions: bigint;
    reputation: Reputation;
    loansTaken: bigint;
    profileCreatedAt: Time;
    activeLoans: bigint;
} {
    return {
        id: value.id,
        principal: value.principal,
        loansGiven: value.loansGiven,
        name: value.name,
        badges: value.badges,
        trustScore: value.trustScore,
        successfulCompletions: value.successfulCompletions,
        reputation: from_candid_Reputation_n26(_uploadFile, _downloadFile, value.reputation),
        loansTaken: value.loansTaken,
        profileCreatedAt: value.profileCreatedAt,
        activeLoans: value.activeLoans
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    offeredInterestRate: number;
    status: _RequestStatus;
    createdAt: _Time;
    collateralType: _AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    assetType: _AssetType;
    amount: bigint;
}): {
    id: bigint;
    durationDays: bigint;
    offeredInterestRate: number;
    status: RequestStatus;
    createdAt: Time;
    collateralType: AssetType;
    borrower: Principal;
    collateralAmount: bigint;
    assetType: AssetType;
    amount: bigint;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        offeredInterestRate: value.offeredInterestRate,
        status: from_candid_RequestStatus_n7(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        collateralType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.collateralType),
        borrower: value.borrower,
        collateralAmount: value.collateralAmount,
        assetType: from_candid_AssetType_n9(_uploadFile, _downloadFile, value.assetType),
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ada: null;
} | {
    bnb: null;
} | {
    btc: null;
} | {
    dot: null;
} | {
    eth: null;
} | {
    sol: null;
} | {
    xrp: null;
} | {
    matic: null;
} | {
    aluminum: null;
} | {
    avax: null;
} | {
    gold: null;
} | {
    link: null;
} | {
    platinum: null;
} | {
    silver: null;
} | {
    copper: null;
} | {
    palladium: null;
}): AssetType {
    return "ada" in value ? AssetType.ada : "bnb" in value ? AssetType.bnb : "btc" in value ? AssetType.btc : "dot" in value ? AssetType.dot : "eth" in value ? AssetType.eth : "sol" in value ? AssetType.sol : "xrp" in value ? AssetType.xrp : "matic" in value ? AssetType.matic : "aluminum" in value ? AssetType.aluminum : "avax" in value ? AssetType.avax : "gold" in value ? AssetType.gold : "link" in value ? AssetType.link : "platinum" in value ? AssetType.platinum : "silver" in value ? AssetType.silver : "copper" in value ? AssetType.copper : "palladium" in value ? AssetType.palladium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repaid: null;
} | {
    active: null;
} | {
    partial: null;
} | {
    defaulted: null;
}): AgreementStatus {
    return "repaid" in value ? AgreementStatus.repaid : "active" in value ? AgreementStatus.active : "partial" in value ? AgreementStatus.partial : "defaulted" in value ? AgreementStatus.defaulted : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    late: null;
} | {
    missed: null;
} | {
    onTime: null;
}): RepaymentStatus {
    return "late" in value ? RepaymentStatus.late : "missed" in value ? RepaymentStatus.missed : "onTime" in value ? RepaymentStatus.onTime : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    available: null;
} | {
    matched: null;
}): LoanStatus {
    return "cancelled" in value ? LoanStatus.cancelled : "completed" in value ? LoanStatus.completed : "available" in value ? LoanStatus.available : "matched" in value ? LoanStatus.matched : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    novice: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
}): Reputation {
    return "bronze" in value ? Reputation.bronze : "novice" in value ? Reputation.novice : "gold" in value ? Reputation.gold : "diamond" in value ? Reputation.diamond : "platinum" in value ? Reputation.platinum : "silver" in value ? Reputation.silver : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    matched: null;
}): RequestStatus {
    return "cancelled" in value ? RequestStatus.cancelled : "open" in value ? RequestStatus.open : "completed" in value ? RequestStatus.completed : "matched" in value ? RequestStatus.matched : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Repayment>): Array<Repayment> {
    return value.map((x)=>from_candid_Repayment_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BorrowRequest>): Array<BorrowRequest> {
    return value.map((x)=>from_candid_BorrowRequest_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanListing>): Array<LoanListing> {
    return value.map((x)=>from_candid_LoanListing_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n24(_uploadFile, _downloadFile, x));
}
function to_candid_AssetType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Reputation_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reputation): _Reputation {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    loansGiven: bigint;
    name: string;
    badges: Array<Badge>;
    trustScore: bigint;
    successfulCompletions: bigint;
    reputation: Reputation;
    loansTaken: bigint;
    profileCreatedAt: Time;
    activeLoans: bigint;
}): {
    id: bigint;
    principal: Principal;
    loansGiven: bigint;
    name: string;
    badges: Array<_Badge>;
    trustScore: bigint;
    successfulCompletions: bigint;
    reputation: _Reputation;
    loansTaken: bigint;
    profileCreatedAt: _Time;
    activeLoans: bigint;
} {
    return {
        id: value.id,
        principal: value.principal,
        loansGiven: value.loansGiven,
        name: value.name,
        badges: value.badges,
        trustScore: value.trustScore,
        successfulCompletions: value.successfulCompletions,
        reputation: to_candid_Reputation_n35(_uploadFile, _downloadFile, value.reputation),
        loansTaken: value.loansTaken,
        profileCreatedAt: value.profileCreatedAt,
        activeLoans: value.activeLoans
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reputation): {
    bronze: null;
} | {
    novice: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
} {
    return value == Reputation.bronze ? {
        bronze: null
    } : value == Reputation.novice ? {
        novice: null
    } : value == Reputation.gold ? {
        gold: null
    } : value == Reputation.diamond ? {
        diamond: null
    } : value == Reputation.platinum ? {
        platinum: null
    } : value == Reputation.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    ada: null;
} | {
    bnb: null;
} | {
    btc: null;
} | {
    dot: null;
} | {
    eth: null;
} | {
    sol: null;
} | {
    xrp: null;
} | {
    matic: null;
} | {
    aluminum: null;
} | {
    avax: null;
} | {
    gold: null;
} | {
    link: null;
} | {
    platinum: null;
} | {
    silver: null;
} | {
    copper: null;
} | {
    palladium: null;
} {
    return value == AssetType.ada ? {
        ada: null
    } : value == AssetType.bnb ? {
        bnb: null
    } : value == AssetType.btc ? {
        btc: null
    } : value == AssetType.dot ? {
        dot: null
    } : value == AssetType.eth ? {
        eth: null
    } : value == AssetType.sol ? {
        sol: null
    } : value == AssetType.xrp ? {
        xrp: null
    } : value == AssetType.matic ? {
        matic: null
    } : value == AssetType.aluminum ? {
        aluminum: null
    } : value == AssetType.avax ? {
        avax: null
    } : value == AssetType.gold ? {
        gold: null
    } : value == AssetType.link ? {
        link: null
    } : value == AssetType.platinum ? {
        platinum: null
    } : value == AssetType.silver ? {
        silver: null
    } : value == AssetType.copper ? {
        copper: null
    } : value == AssetType.palladium ? {
        palladium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
